# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chatroom_pb2 as chatroom__pb2


class ChatRoomStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/chatroom.ChatRoom/CreateUser',
                request_serializer=chatroom__pb2.User.SerializeToString,
                response_deserializer=chatroom__pb2.requestReply.FromString,
                )
        self.Login = channel.unary_unary(
                '/chatroom.ChatRoom/Login',
                request_serializer=chatroom__pb2.User.SerializeToString,
                response_deserializer=chatroom__pb2.requestReply.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/chatroom.ChatRoom/DeleteUser',
                request_serializer=chatroom__pb2.User.SerializeToString,
                response_deserializer=chatroom__pb2.requestReply.FromString,
                )
        self.ListUsers = channel.unary_unary(
                '/chatroom.ChatRoom/ListUsers',
                request_serializer=chatroom__pb2.UserList.SerializeToString,
                response_deserializer=chatroom__pb2.requestReply.FromString,
                )
        self.SendText = channel.unary_unary(
                '/chatroom.ChatRoom/SendText',
                request_serializer=chatroom__pb2.Text.SerializeToString,
                response_deserializer=chatroom__pb2.requestReply.FromString,
                )


class ChatRoomServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatRoomServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=chatroom__pb2.User.FromString,
                    response_serializer=chatroom__pb2.requestReply.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=chatroom__pb2.User.FromString,
                    response_serializer=chatroom__pb2.requestReply.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=chatroom__pb2.User.FromString,
                    response_serializer=chatroom__pb2.requestReply.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=chatroom__pb2.UserList.FromString,
                    response_serializer=chatroom__pb2.requestReply.SerializeToString,
            ),
            'SendText': grpc.unary_unary_rpc_method_handler(
                    servicer.SendText,
                    request_deserializer=chatroom__pb2.Text.FromString,
                    response_serializer=chatroom__pb2.requestReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatroom.ChatRoom', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatRoom(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatroom.ChatRoom/CreateUser',
            chatroom__pb2.User.SerializeToString,
            chatroom__pb2.requestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatroom.ChatRoom/Login',
            chatroom__pb2.User.SerializeToString,
            chatroom__pb2.requestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatroom.ChatRoom/DeleteUser',
            chatroom__pb2.User.SerializeToString,
            chatroom__pb2.requestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatroom.ChatRoom/ListUsers',
            chatroom__pb2.UserList.SerializeToString,
            chatroom__pb2.requestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatroom.ChatRoom/SendText',
            chatroom__pb2.Text.SerializeToString,
            chatroom__pb2.requestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
